version: 1.0.{build}

image: Visual Studio 2017

environment:
  matrix:
  - cmake_generator: Visual Studio 16 2019
    cmake_arch: Win32
    config: Release
    arch: vs2019-x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

  - cmake_generator: Visual Studio 16 2019
    cmake_arch: x64
    config: Release
    arch: vs2019-x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

  - cmake_generator: Visual Studio 15 2017
    cmake_arch: Win32
    config: Release
    arch: vs2017-x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

  - cmake_generator: Visual Studio 15 2017
    cmake_arch: x64
    config: Release
    arch: vs2017-x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

  - cmake_generator: Visual Studio 14 2015
    cmake_arch: Win32
    config: Release
    arch: vs2015-x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

  - cmake_generator: Visual Studio 14 2015
    cmake_arch: x64
    config: Release
    arch: vs2015-x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

init:
  - git config --global core.autocrlf true

build_script:
  - cmake -G"%cmake_generator%" -A"%cmake_arch%" -H. -Bbuild
  #- cmake --build build --config "%config%"
  - msbuild build\minigsf.sln /t:build /p:Configuration="%config%" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - ps: $env:my_version = "$env:APPVEYOR_BUILD_VERSION-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
  - set package_name=minigsf-%my_version%-%arch%
  - copy "build\%config%\minigsf.exe" .
  - 7z a %package_name%.zip minigsf.exe README.md LICENSE

artifacts:
  - path: $(package_name).zip
    name: $(arch)
